#ifndef _JERRYSCRIPT_MBED_DRIVERS_SET_INTERVAL_H
#define _JERRYSCRIPT_MBED_DRIVERS_SET_INTERVAL_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

DECLARE_GLOBAL_FUNCTION(setInterval);
DECLARE_GLOBAL_FUNCTION(clearInterval);

#endif  // _JERRYSCRIPT_MBED_DRIVERS_SET_INTERVAL_H
