EXTRAS=
ifneq ($(EXTRAS),)
EXTRAS_CLEAN=$(strip $(EXTRAS);../../../source)
else
EXTRAS_CLEAN=../../../source
endif

.PHONY: all

all:
	cd jerryscript/targets/mbedos5 && rm -f source/js_encoded.cpp && rm -f source/main.cpp && make BOARD=$(BOARD) EXTRA_SRC="$(EXTRAS_CLEAN)" EXTERN_BUILD_DIR=../../../out/$(BOARD) NO_JS=1
